apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
  namespace: kube-ops
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "root123"
  UI_SECRET: "42VPEolTxWOEouiW"
  SECRET_KEY: "VTXdK8CdXADDwS9G"
  CONFIG_PATH: /etc/jobservice/app.conf
  REGISTRY_URL: http://registry:5000
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  LOG_DIR: /var/log/jobs
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "http://reg.mydomain.com"
  TOKEN_URL: http://ui
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
